Recent changes for issue 1
BstLabs/medium-articles pull request #2
Opened 2022-02-04 12:42 UTC by ShahriyarR

Fixes #1

2022-02-04 13:36 UTC, asterkin requested changes

2022-02-04 13:36 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +    name: str, birth: str, *manufacturers: Manufacturer, **dates: str
I still think it would be better to define it as
```
def generate(name: str, birth_date: str, **vaccinations: Manufacturer):
```
using dates a names in **kwargs. Eventually, we could support dict[date, Manufacturer] instead of plain **kwargs. See also my comment below.
I would approve a slight delay for adding support for these features since it would look really cool.

2022-02-04 13:36 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +This is quite intuitive isn't it? Thinking about CLI call, it will look like: `./cli qr-code generate Shako 1989-10-24 pfizer pfizer 1st_dosage=2021-01-01 2nd_dosage=2021-06-01`
You do not need ./cli here. Your entry point could be called for example green-badge generate ...
At least this is how we call it in Israel, or you may call vacination generate-qr ... or something like that. ./cli is just redundant.

2022-02-07 11:32 UTC, ShahriyarR commented on how_to_convert_python_functions/article.md
> +    name: str, birth: str, *manufacturers: Manufacturer, **dates: str
This is postponed as per our discussion.

2022-02-07 11:42 UTC, ShahriyarR commented
@asterkin PTAL

2022-02-08 12:35 UTC, ShahriyarR commented
@shruti1807 @slichtma Please read the article here:
https://github.com/BstLabs/medium-articles/blob/issue-1/how_to_convert_python_functions/article.md

2022-02-09 12:27 UTC, shruti1807 commented
Hey Shako,

I am going through it . Will get back to you by tomorrow.

Thanks
Shruti

On Tue, Feb 8, 2022 at 6:05 PM Shahriyar Rzayev ***@***.***>
wrote:

> @shruti1807 <https://github.com/shruti1807> @slichtma
> <https://github.com/slichtma> Please read the article here:
>
> https://github.com/BstLabs/medium-articles/blob/issue-1/how_to_convert_python_functions/article.md
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BstLabs/medium-articles/pull/2#issuecomment-1032561451>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGHRWYJG6HTNJGKB2VVRTUTU2EEYTANCNFSM5NRVZHJA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-09 13:11 UTC, ShahriyarR commented
@shruti1807 I will push recent changes and ping you :)

2022-02-09 13:16 UTC, ShahriyarR commented
@shruti1807 updated. thanks.

2022-02-09 13:16 UTC, ShahriyarR commented
@asterkin PTAL

2022-02-10 09:59 UTC, asterkin requested changes

2022-02-10 09:59 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +We want to extend this article by using [dynacli](https://pypi.org/project/dynacli/).
Should be DynaCLI to preserve brand consistency

2022-02-10 09:59 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +To keep it simple dynacli generates help messages from the Python function docstrings and the function arguments are converted to CLI commands.
DynaCLI

2022-02-10 09:59 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +With [dynacli](https://pypi.org/project/dynacli/) we can skip 2nd part by designing our functions to be CLI-friendly.
DynaCLI

2022-02-10 09:59 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +First off all, we would like to restructure the CLI - thinking about CLI there should be `./qr-code` then `green-badge` feature-set(actual Python package) it is for storing all commands,
better "grouping all command from one feature together" than "storing"

2022-02-10 09:59 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +
You discussed a feature of using dynacli init to bootstrap a new CLI project. I assume it's not there yet.

2022-02-10 09:59 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +    date: datetime
date class would be enough; we do not store time

2022-02-10 09:59 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +    birth: str
better birth_date

2022-02-10 09:59 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +    vaccination: list[Vaccination]
should be vaccinations (plural)

2022-02-10 09:59 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +def generate(first_name: str, last_name: str, birthdate: str,  **vaccination: str) -> None:
vaccinations (plural)

2022-02-10 09:59 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +        birth=birthdate,
birth_date, vaccinations

2022-02-10 09:59 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +
In this case, supporting Enums would be nicer and I did not get what you benefit from literals. I do not object supporting them in DynaCLI, but we have to be clear and consistent.

2022-02-10 09:59 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +You only enjoy your Python code, nothing more.
As we discussed, you need to add a small paragrpah on Open Closed principle justifying keeping each command in a separate module.

2022-02-10 13:26 UTC, ShahriyarR commented on how_to_convert_python_functions/article.md
> +You only enjoy your Python code, nothing more.
I guess it is already there

2022-02-10 13:27 UTC, ShahriyarR commented on how_to_convert_python_functions/article.md
> +
But in your edition the need for Enum is just eliminated - i.e we can not use Enum type with **kwargs in current DynaCLI implementation. That's why the need to the Enum type just disappeared in this article.

2022-02-10 16:41 UTC, asterkin commented on how_to_convert_python_functions/article.md
> +
I do not understand why we cannot use Enum or any type in **kwargs: <type> and if this is the case, let's fix it. The whole idea was that the **kwargs could be of any type and you control it (yes, not argparse, but the user will not notice). What I'm missing?

2022-02-10 17:11 UTC, ShahriyarR commented on how_to_convert_python_functions/article.md
> +
The problem is `**kwargs: EnumType` -> DynaCLI originally registers Enum type as choices and we did it either *args or a positional argument, and with `date=[choices]` it does not work.

2022-02-10 17:47 UTC, ShahriyarR commented on how_to_convert_python_functions/article.md
> +
Nope, it is not even started.

2022-02-14 14:20 UTC, slichtma commented on how_to_convert_python_functions/article.md
> +You only enjoy your Python code, nothing more.
I can propose a number of polishing edits to the green pass/dynacli article. @ShahriyarR 
, is the doc good for me to pull, or do you need to merge outstanding edits first?

2022-02-21 07:00 UTC, ShahriyarR commented
I have grabbed @shruti1807 and @slichtma changes and merged to my branch.
Now the text should be okay - remaining thing is to make code changes to our sample app.
The rest is good to go. Thanks for your help guys you are awesome :)

2022-02-22 15:36 UTC, ShahriyarR commented
@asterkin @shruti1807 @slichtma 
This is a updated version with small additions - I have merged your text as well.
Please review.

2022-02-23 11:07 UTC, ShahriyarR commented
If we are good to go, please approve this PR and then I need to merge this PR, make this repo public.
Finally we need to publish this article and prepare next ones.
@asterkin @slichtma @shruti1807

2022-02-23 19:32 UTC, slichtma approved these changes
Text all looks good/

2022-02-24 09:28 UTC, asterkin approved these changes

2022-02-24 09:28 UTC, asterkin commented on how_to_convert_python_functions/code/green_badge/generate.py
> +            Vaccination(manufacturer=manufacturer, date=datetime.strptime(date, "%Y-%m-%d"))
Ideally, it should print a nice error message if one of vaccination pairs contains wrong or duplicate date. But you could leave it as a comment to keep the code simple.

2022-02-24 11:19 UTC, merged